# Funding is intentionally disabled for the public release surface so this
# repository does not publish a personal sponsor handle. Donations are not
# required and do not create support, maintenance, warranty, or priority duties.
